---
- name: Setting locales to be generated
  debconf:
    name: locales
    question: locales/locales_to_be_generated
    value: "{{ locale_generated|join(', ') }}"
    vtype: multiselect
  register: locale_generated_debconf

- name: dpkg-reconfigure locales
  block:
  - template:
      dest: '/etc/locale.gen'
      src: locale.gen.j2
      owner: root
      group: root
      mode: 0644
  - debconf:
      name: locales
      question: locales/locales_to_be_generated
      value: "{{ locale_generated|join(', ') }}"
      vtype: multiselect
  - command: dpkg-reconfigure -fnoninteractive locales
  when: locale_generated_debconf is changed

- name: Setting default locale
  template:
    dest: '/etc/default/locale'
    src: locale.j2
    owner: root
    group: root
    mode: 0644

- name: Update locales debconf
  debconf:
    name: locales
    question: locales/default_environment_locale
    value: '{{ locale_default.LANG }}'
    vtype: select

# vim: set ts=2 sw=2 et:
